In [7]:
import pandas as pd
import tarfile

## Read the data

In [ ]:
with tarfile.open("data/en-de.tar.gz", "r:*") as tar:
    tar.readnames

In [28]:
with tarfile.open("data/en-de.tar.gz", "r:*") as tar:
    separator = "\t"
    df_dev = pd.read_csv(tar.extractfile('en-de/dev.ende.df.short.tsv'),
                         on_bad_lines='skip',
                         sep = separator,
                        index_col = "index")

In [29]:
df_dev

,original,translation,scores,mean,z_scores,z_mean,model_scores
index,,,,,,,
0,"Simultaneously, the Legion took part to the pa...",Gleichzeitig nahm die Legion an der Befriedung...,"[20, 35, 30, 100, 100, 100]",64.166667,"[-2.4423814053504707, -1.5862748751298898, -1....",-0.312186,-0.298508
1,He also begins an affair with Veronica Harring...,Er beginnt auch eine Affäre mit Veronica Harri...,"[91, 100, 100, 70, 71, 69]",83.500000,"[0.5487023851101287, 0.9907560639635818, 0.955...",-0.401581,-0.214255
2,The urban morphology of these two local waters...,Die urbane Morphologie dieser beiden lokalen W...,"[95, 100, 95, 72, 95, 100]",92.833333,"[0.7172141479529794, 0.9907560639635818, 0.746...",0.275414,-0.424506
3,Important finds included a bronze axe in Wellw...,Wichtige Funde waren eine Bronzeaxt in Wellwoo...,"[91, 100, 100, 100, 80, 100]",95.166667,"[0.5487023851101287, 0.9907560639635818, 0.955...",0.580925,-0.375554
4,"Previously, Englishmen had drunk mainly dark s...",Früher hatten Engländer vor allem dunkle Stout...,"[29, 40, 50, 64, 66, 62]",51.833333,"[-2.063229938954057, -1.3880417259688536, -1.1...",-1.895129,-0.468722
...,...,...,...,...,...,...,...
995,"The gang absconded with $2,000 cash in the sec...",Die Bande flüchtete mit $2.000 Bargeld in den ...,"[70, 65, 95, 100, 77, 100]",84.500000,"[-0.33598436981483737, -0.3968759801636721, 0....",0.088897,-0.259579
996,The Irish settlers arrives from Northern Irela...,Die irischen Siedler kommen kurz nach den Loya...,"[100, 95, 95, 85, 81, 100]",92.666667,"[0.9278538515065428, 0.7925229148025456, 0.746...",0.614926,-0.269823
997,Volcanics include dacite breccia and small rem...,Zu den Vulkanen gehören Dacite Breccia und kle...,"[50, 50, 40, 100, 84, 92]",69.333333,"[-1.1785431840290908, -0.991575427646781, -1.5...",-0.484296,-0.412556
998,The Fort Concho Museum acquired the Schoolhous...,Das Fort Concho Museum erwarb 1946 das Schulha...,"[100, 91, 95, 95, 77, 100]",93.000000,"[0.9278538515065428, 0.6339363954737166, 0.746...",0.560427,-0.208066
999,"Motor lorries caked with dust, also drove west...","Motorlastwagen mit Staub verkleidet, fuhr auch...","[70, 55, 55, 100, 75, 100]",75.833333,"[-0.33598436981483737, -0.7933422784857447, -0...",-0.261842,-0.511049